# Site settings
title: YPRL Python Tutorial Workbooks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  These are the online workbooks that will be used for the YPRL Python tutorials.
baseurl: "/yprl-python-workbooks" # the subpath of your site, e.g. /blog/
url: "https://lmika.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
