# Site settings
title: YPRL Python Tutorial Workbooks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  These are the online workbooks that will be used for the YPRL Python tutorials.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
